name: JupyterBook
channels:
  - default
  - conda-forge
dependencies:
  - python
  - sphinx
  - pip
  - pandas
  - matplotlib
  - scipy
  - numpy
  - sympy
  - seaborn
  - statsmodels
  - pip:
    - quantecon
    - git+https://github.com/ExecutableBookProject/jupyter-book
    - linearmodels
    - lmdiag
    - see
    - wooldridge
    - gapminder
    - ghp-import
