name: JupyterBook
channels:
  - default
  - conda-forge
dependencies:
  - python
  - sphinx == 3.2.1
  - pip
  - pandas
  - matplotlib
  - scipy
  - numpy
  - sympy
  - seaborn
  - statsmodels
  - pip:
    - quantecon
    - jupyter-book
    - linearmodels
    - lmdiag
    - see
    - wooldridge
    - gapminder
    - ghp-import
    - git+https://github.com/spring-haru/py4etrics
